name: Build for Ubuntu latest aarch64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        targets: |
          aarch64-unknown-linux-gnu
          aarch64-unknown-linux-musl

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc-aarch64-linux-gnu libc6-dev-arm64-cross \
          musl-tools

    - name: Configure Cargo for cross-compilation
      run: |
        mkdir -p ~/.cargo
        cat >> ~/.cargo/config.toml << EOF
        [target.aarch64-unknown-linux-gnu]
        linker = "aarch64-linux-gnu-gcc"
        EOF

    - name: Build project
      env:
        CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
        CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
        AR_aarch64_unknown_linux_gnu: aarch64-linux-gnu-ar
        CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
      run: |
        cargo build --release --target aarch64-unknown-linux-gnu

    - name: Verify build
      run: |
        file target/aarch64-unknown-linux-gnu/release/nbted

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nbted-aarch64
        path: target/aarch64-unknown-linux-gnu/release/nbted

    - name: Build static MUSL binary
      run: |
        rustup target add aarch64-unknown-linux-musl
        cargo build --release --target aarch64-unknown-linux-musl

    - name: Upload MUSL artifact
      uses: actions/upload-artifact@v4
      with:
        name: nbted-aarch64-musl
        path: target/aarch64-unknown-linux-musl/release/nbted